name: TestCompile
on: push
jobs:
  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          sketch-names: Blumentopf_sketch.ino
          required-libraries:
